### ISSUE TITLE
Getting Resource not found exception.

### ISSUE THREAD

**Issue by KhadkaRabindra** [hamidness/restring#19]
When I used this library with webview with javascript enabled , while clicking the spinner inside the webview  I get this exception
Fatal Exception: android.content.res.Resources$NotFoundException
Resource ID #0x0

**Comment by paularius** [comment]
@KhadkaRabindra Is this issue resolved? Because I have the exact same problem.
Thanks

**Comment by KhadkaRabindra** [comment]
yes @paularius remove this when you are using webview
@Override
protected void attachBaseContext(Context newBase) {
    super.attachBaseContext(Restring.wrapContext(newBase));
}
